### ISSUE TITLE
how to select a combo-box ?

### ISSUE THREAD

**Issue by SanjeevKumarmn** [jalian-systems/marathon-demo#1]
could you pls give me an example of how to select an dropdown value from combox box using java driver -selenium? appreciate if this can be based on swingset3 app.

**Comment by kdmurthy** [comment]
Have a look at:
http://marathontesting.com/documentation/?section=javaswing-components

That should help.

Can you please use the google groups for these discussion (I cc'ed this
mail).

-- KD

--
Dakshinamurthy Karra
Jalian Systems Pvt. Ltd.
1st Floor, #457, 3rd Cross
5th Main, 5th Block
H.B.R Layout
Bangalore - 560043
INDIA
W: http://www.jaliansystems.com
W: http://www.marathontesting.com

**Comment by SanjeevKumarmn** [comment]
Sure Murthy, thanks for the response. Pls label this issue as a question for future readers.
